### ISSUE TITLE
Installing wps-office via pacman gives error: "No space left on device"

### ISSUE THREAD

**Issue by xarai** [KaOS-Community-Packages/wps-office#1]
*_Sollution: *_
Download the zipfile (wps-office-master.zip) to you're local drive. 
Then extract the zipfile. 
Open konsole, go to directory where the PKBUILD file can be found. 
Use this command: makepkg -c -i -s -r
Type you're password when the system ask for it.
Ready...

==> Making package: wps-office 10.1.0.5503_a20p2-1 (Thu Feb  4 21:11:48 CET 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading wps-office_10.1.0.5503~a20p2_x86_64.tar.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  153M  100  153M    0     0  7313k      0  0:00:21  0:00:21 --:--:-- 9085k
==> Validating source files with sha512sums...
    wps-office_10.1.0.5503~a20p2_x86_64.tar.xz ... Passed
==> Extracting sources...
  -> Extracting wps-office_10.1.0.5503~a20p2_x86_64.tar.xz with bsdtar
==> Starting prepare()...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Purging unwanted files...
  -> Removing empty directories...
  -> Compressing man and info pages...
  -> Stripping unneeded symbols from binaries and libraries...
==> Creating package "wps-office"...
  -> Generating .PKGINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: wps-office 10.1.0.5503_a20p2-1 (Thu Feb  4 21:15:12 CET 2016)
==> Installing package wps-office with pacman -U...

**Comment by Israphel** [comment]
Well I do the classic makepkg with no arguments and it works

**Comment by Israphel** [comment]
Maybe your /tmp is full. When you did manual you didn't use /tmp

**Comment by xarai** [comment]
Thanks for the great WPS-office Package. 
I was looking a long time for it. 
It works like a charme. 
Thanks again.

**Comment by demmm** [comment]
Just to clarify, kcp builds in /tmp, which often is not large enough for big packages like this.
You still can use kcp, as in getting the needed files in a build directory somewhere in your /home
Example:

```
cd ~/dev/build
kcp -g package_name
cd package_name
makepkg -si
```

Use the above method for WPS

**Comment by Israphel** [comment]
Thanks demmm, /tmp is related to total RAM if I recall correctly.
